export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_ALREADY_CLOSED: "TICKET_ALREADY_CLOSED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  RECEIPT_NOT_REVIEWABLE: "RECEIPT_NOT_REVIEWABLE",
  RECEIPT_SUBMIT_FAILED: "RECEIPT_SUBMIT_FAILED"
} as const;
