ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "HAZARD_TICKET_NOT_FOUND": "HAZARD_TICKET_NOT_FOUND",
    "RECEIPT_NOT_FOUND": "RECEIPT_NOT_FOUND",
    "RECEIPT_RETRY_TARGET_FAILED": "RECEIPT_RETRY_TARGET_FAILED",
    "RECEIPT_NOT_REVIEWABLE": "RECEIPT_NOT_REVIEWABLE",
    "HAZARD_TICKET_NOT_CLOSABLE": "HAZARD_TICKET_NOT_CLOSABLE",
    "AUDITOR_READ_ONLY": "AUDITOR_READ_ONLY",
}
